name: 02-01-Simple Workflow
on: 
  workflow_dispatch:
    inputs:
      java-version:
        type: string
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/
