name: simpleworkflow
on: 
  workflow_dispatch:
    inputs:
      java-version:
        type: string
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        run: echo ${{vars.VARIABLE}}

